'use client'

import React, { useEffect, useState } from 'react';

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google';
import ProductsContextComponent from "../../context/productsContext";
import MyNavMenu from '@/components/myNavMenu';
import MobileNav from '@/components/mobileNav';
import Footer from '@/components/footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const [mobileNavbar, setMobileNavbar] = useState(false);

  useEffect(() => {
    if (window.innerWidth < 920) {
      setMobileNavbar(true);
    }
  } , [])

  return (
    <html lang="en">
      <body className={inter.className}>
        <ProductsContextComponent>
          {!mobileNavbar ? <MyNavMenu /> : <MobileNav />}
          {children}
          <Footer />
        </ProductsContextComponent>
      </body>
    </html>
  )
}
