import React from 'react';

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google';
import ProductsContextComponent from "../../context/productsContext";
import MyNavMenu from '@/components/myNavMenu';
import MobileNav from '@/components/mobileNav';
import Header from '@/components/header';
import Footer from '@/components/footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <ProductsContextComponent>
          <Header/>
          {children}
          <Footer />
        </ProductsContextComponent>
      </body>
    </html>
  )
}
